version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  prod-pack:
    jobs:
      - orb-tools/lint:
          filters: *release-filters
      - orb-tools/pack:
          filters: *release-filters
      - shellcheck/check:
          filters: *release-filters
      - orb-tools/continue:
          context: orb-publishing
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: rhems-japan/twingate
          requires:
            - orb-tools/lint
            - orb-tools/pack
            # - orb-tools/review
            - shellcheck/check
          filters: *release-filters

  dev-pack:
    when:
      and:
        - equal: [<< pipeline.git.branch >>, "dev"]
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      # - orb-tools/review
      - shellcheck/check
      - orb-tools/continue:
          context: orb-publishing
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: twingate
          requires:
            - orb-tools/lint
            - orb-tools/pack
            # - orb-tools/review
            - shellcheck/check
