version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  twingate: rhems-japan/twingate@dev:<<pipeline.git.revision>>

executors:
  default:
    machine:
      image: ubuntu-2004:2023.04.2

jobs:
  integration-test:
    executor: default
    steps:
      - checkout
      - twingate/install-twingate
      - twingate/start-twingate
      - twingate/stop-twingate

workflows:
  dev-deploy:
    when:
      and:
        - equal: [<< pipeline.git.branch >>, "dev"]
    jobs:
      - integration-test
      - orb-tools/pack:
          requires:
            - integration-test
      - orb-tools/publish:
          context: orb-publishing
          orb_name: rhems-japan/twingate
          vcs_type: << pipeline.project.type >>
          requires:
            - orb-tools/pack
