version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  production-deploy:
    jobs:
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          context: orb-publishing
          orb_name: rhems-japan/twingate
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          filters: *release-filters
