name: Post to orbs-package

on:
  push:
    tags:
      - "test[0-9]+.[0-9]+.[0-9]"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Access Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_FORGITHUBACTIONS_ID }}
        private_key: ${{ secrets.APP_FORGITHUBACTIONS_KEY }}

    - name: Set Env
      run: echo "ACCESS_TOKEN=`echo ${{ steps.generate_token.outputs.token }}`" >> $GITHUB_ENV

